language: java
install: true
addons:
  sonarqube:
    organization: "mcadams0001-github"
    token:
      secure: "E0OkPTLd8o8rS1hnQ6AY3rvcYawXa9cYqVZUH8UI3G8M9YgDBwfKY9xIsA3txhSrWbT077Uw7E1mYg1m8UAwV2BHZZSsGBYnu7cAzoBJ3QhcRDBmGONPh07N1vmon+WiAEY0dRZg0N+nLCoJ/6erhsY8aG2JU5EoyS6N/kb0BUlKNaFs3mF602cknW53BlnyXCzHo8JiVO4ApyreA9zVUti9jQL4YD1ZOnuZyi7PHi72U/RuMu/1y9gIaH9OgDMzOp8O6o1SOkmjEJ1P4Zed2rGI9Uft26O5oixnySjzcoZW8mHqvNX2lDaj1jT6yf4hBN0wWHL3pKM2bkE5/uBnDYOp8VD+zTZQEWBnyRggZuufIwXvL656qS53mw2Qtlz5puwrgPb1z+c2EQXIfQcY8KYP4w8lg6NYT+7b9i/qxIOtN19A7Zo6E612Bxm+bX8E+fw2BaJBd8/bTAL6BO3ws7VdjsS+fARSn062uD8Ol/myQZ+kSsCMS15uCGmQG3wigtgazvbE0iiBUx0tyy0Pw8QvbJIQvZ6MnM7ZKAjtf59Lb8gYpx15TTM6+0GDtDZcU2K56i+hMImfOW0E9nOYvZ3X7m01kHGEZ1kCPCGqdIcL0S7Ioscj2cLNajeVJkYGY3uvQYXNYQiiy3Frm8ijV+C4e1D90APz0On1KDvg/cw="
jdk:
- oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
deploy:
  provider: heroku
  api_key:
    secure: GC1xkgJN74b//FOcpRr7M0YQvrHNeqQrXj2J5frI6vGEiKTKlhmLG3xdQufIPhFQPLWKrRlv51XAwHbqNd3xRL4bU9aAIDgPLD/OVs3t4kuXyAVh6mRssi3UW1DW3mcXPBbroNZOE2qjvuShG83mU5YzfnvV3lBBKmmb+kXltnmUgjAUcAANNmvmRCXfU+PSkE3ymWDypoMg3W/Tryz9oNa38mPya6VooLB5Y15h8SMRFn+e7YhZHFhxDPn+EXZlIX+MyxL9GLp+broA/YkyG5ODgDeZIQTL7WKvW9PFgtFbXWPutu4jmrKPPV2yArPo8F+3gXlQX5Nxaynq0k35T8prrdspGibZmlqqomhBlNwmipGIG7Vnu759d0HuJV+tgcRTM5r4b5SBwBcW8RIrL5OE0EUtw5syoPPxRjhnLQxXoF3c5YyNslX3mFGB92qDMuRnjauc0+NSG+GSZ+6K+fQ3WKoBtKarXLfI0SE6Y8VEMhw7xZ09AAc8SGEGJbntLsMVSp4zxt0AlkjUHEhcYBJHCrP7Y5Td9z4kvvFoGj9poqYlSIkLfD+gaWPNO8nRtpDUpP0V+qoWhWN3f33KXOLtqdmxO6ReTdD+9ZWOUsGZ/6DQhkgM1hxvGaYlrUBlv/0dxTn9kNX9r5SNOrBd2lv6kYqzuiT6iSTLvVKdcBw=
  app: sleepy-forest-52031
