language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: dJHyE8o1AAxIagW5I/BcqOLnzhvJ2ylU70EP5rIDoBczlPVSNO8xRX3dLhdnYYz/ykvIFKXjgcgyVWbDwBfb9NsgJNZ296d4JIxf4OJJM1z+qvVbMDVagg4FTy5997XqXpjLSLbT2tXKMaYDr+JdI+yTUZXhuBm0vXXo5VuLevBeWL/mnPpOvUaeH4hK5QNvxSSuJ1BMF2O5xIPlmonyUfrl6dXiAx/VzW9e0dv9OPcpsdB114d3XlEyV8sV0UfvK56fI4mCf2Xhau/RPP/xOvYZcDCX/LPdn8pFLaXI3A1aVdyt56Od1L5ETy/z0xAwwBeuseD6dcsn4CfbEGB4+UNJOaw22kG270TYggOugsCt+DmXTACXzCT7YlqnrNcjeBi03DLv2i2vjYwRuGxm7RrRnIib4K86GEKnoYBWde3K+yxy1BbwBfcyZr7wffY1MSirD8AqWbb0+iSYfnfS4yWx40qf621dHlDKSVPkVUBekKmTNvKYilKz/pyRugyzW8xv7V0wvW+UAYrjN2m3DprwXlM8uxPh/Z+wPtbIdD2hbdYkBmqXJKLpzzoicZ3np89lZdGMkxfy51FYtPij+lUZu4NyGGMX2TIAUC0+xD+11i8KVqhkdKXddpCbtDvrq9ziRU8iqoc49jKRgMUZwN2n8qZBoUJklZlCsMPAHhs=
  app: currencyconverter
