language: java
sudo: true
install: true
addons:
  sonarcloud:
    organization: "mcadams0001-github"
    token:
      secure: "3MeIOcqvA++9ofYaYZrm7Kn92/HDXcvvBhKSvS1Oj6RZeUaA1xcxDtXfB7JoU6WjCsgMMt5D284Y3yOP/ywnCMaWmmhp8WNLJRELd+guv2iug6Wf0gOkkw71v+cHiUJk3UEGaQ5lqEYdSR7YP0CPLyvaQhqXKDtbLUd2PA1gy7h9IoixeOun4rA7FAhetye+R/nd8txKOT65rCSq7aSW8CnxhkHSn+LSlduW+LL/7TSdgti6F2ZoECyaGPMDdzwgXAYL/oUVwgsFLA7nccSE8iP5TY3hBmA1bn3QYpEIiZSG/GwYFyv/3gCRlho6CloSBZjhDAt86SvNgdhmvjBDmUiblT6D4+s7r3JFNuMNFkbkzfvy5elDbOIPjcBHXyNGIfqHmK9B4h/XSF8/+mqdVvtbYyBeSjKzOfEAr00B29hVk/kHlEK+PUDBOaqcMGMu7azqUnVBjlwH9P5sJuJWMcODPFU8HD5OBtJb0RtvaEwSfiJ1RgkHmi90lUJoCrSpv0vcFMNbP64HlupqXplk5p9mW2gDksSfW0r3cvE97bIi9r6PHMK+YIej0YK75vZLqgqJiCix2ZejGa/abnTsDPLH1ELcLGXBe1AeB/ZLSQ3RD7+k2RuDeVZwuh6F1ica/K/5K39IDzoaKHotNc9OdLC1RjwgqsXi7JIOjj0LZfk="
jdk:
- openjdk10
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Ptravis
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
deploy:
  provider: heroku
  api_key:
    secure: GC1xkgJN74b//FOcpRr7M0YQvrHNeqQrXj2J5frI6vGEiKTKlhmLG3xdQufIPhFQPLWKrRlv51XAwHbqNd3xRL4bU9aAIDgPLD/OVs3t4kuXyAVh6mRssi3UW1DW3mcXPBbroNZOE2qjvuShG83mU5YzfnvV3lBBKmmb+kXltnmUgjAUcAANNmvmRCXfU+PSkE3ymWDypoMg3W/Tryz9oNa38mPya6VooLB5Y15h8SMRFn+e7YhZHFhxDPn+EXZlIX+MyxL9GLp+broA/YkyG5ODgDeZIQTL7WKvW9PFgtFbXWPutu4jmrKPPV2yArPo8F+3gXlQX5Nxaynq0k35T8prrdspGibZmlqqomhBlNwmipGIG7Vnu759d0HuJV+tgcRTM5r4b5SBwBcW8RIrL5OE0EUtw5syoPPxRjhnLQxXoF3c5YyNslX3mFGB92qDMuRnjauc0+NSG+GSZ+6K+fQ3WKoBtKarXLfI0SE6Y8VEMhw7xZ09AAc8SGEGJbntLsMVSp4zxt0AlkjUHEhcYBJHCrP7Y5Td9z4kvvFoGj9poqYlSIkLfD+gaWPNO8nRtpDUpP0V+qoWhWN3f33KXOLtqdmxO6ReTdD+9ZWOUsGZ/6DQhkgM1hxvGaYlrUBlv/0dxTn9kNX9r5SNOrBd2lv6kYqzuiT6iSTLvVKdcBw=
  app: sleepy-forest-52031
