language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: "mcadams0001-github"
    token:
      secure: DYwErVoCfX8bwE37/HIVh9hhBJvLY7jPRxTeJ/twsxm79hdiDKI7Mb2jehvkzR9tlcJim+Z5NmJKQnFxENBRVn//ScD6x7/tRa64gEg31pJnTsKVEYLQdAF6CfJdCqea9BpXOAQLeL2Zt1SwxQYkV1u9KjAPksfcLuJEhRN4OioSnagd+3SjBBy54ERmoW+YgwGteh44tKRhczvh2HUUdEPLOFrOfT/EO2UE5WjIjgdzzZBmzTUFmWk7b6x/enxXX3qWwr5fd+z6J5EO37aobbG6i1bDaW6W7oL3Rf9QQ5+/iNv+RB49xznVXdwzNdtSokO6gH4Q7F9JHzLmEbP5HTmWlGOCp6LtRc6XMaCwR89NVFROVpH0jiSPJAsAfbjMlVf6/ZcIz5Zc02MqfBCQQ1SgAAFbt5MNrVF8q6clwCF7NcXMksNGUHBZOaQW3TuZNsyS7rqM7lMA3YXy6AogQM8bdgvSISsqmxv+ikRz1ujJ7aT0jqQC8N9KlR+nko30MrGUu/THugNohuxCJLa6p9Hqy/keN8xAjUXjtp9kQyQk+p6b4Bqw3JFMZApMc3Mxit3/XEsaCjsE2cFLWAQ3RDPgEg+1sByt17JBeSmRPmtcHQIYHtSNSTakXa8mRtg2UuEE9zV3IdF4HzmgoiyQA99lWDoi6NVZiB/2WL72MFg=
jdk:
- oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
deploy:
  provider: heroku
  api_key:
    secure: GC1xkgJN74b//FOcpRr7M0YQvrHNeqQrXj2J5frI6vGEiKTKlhmLG3xdQufIPhFQPLWKrRlv51XAwHbqNd3xRL4bU9aAIDgPLD/OVs3t4kuXyAVh6mRssi3UW1DW3mcXPBbroNZOE2qjvuShG83mU5YzfnvV3lBBKmmb+kXltnmUgjAUcAANNmvmRCXfU+PSkE3ymWDypoMg3W/Tryz9oNa38mPya6VooLB5Y15h8SMRFn+e7YhZHFhxDPn+EXZlIX+MyxL9GLp+broA/YkyG5ODgDeZIQTL7WKvW9PFgtFbXWPutu4jmrKPPV2yArPo8F+3gXlQX5Nxaynq0k35T8prrdspGibZmlqqomhBlNwmipGIG7Vnu759d0HuJV+tgcRTM5r4b5SBwBcW8RIrL5OE0EUtw5syoPPxRjhnLQxXoF3c5YyNslX3mFGB92qDMuRnjauc0+NSG+GSZ+6K+fQ3WKoBtKarXLfI0SE6Y8VEMhw7xZ09AAc8SGEGJbntLsMVSp4zxt0AlkjUHEhcYBJHCrP7Y5Td9z4kvvFoGj9poqYlSIkLfD+gaWPNO8nRtpDUpP0V+qoWhWN3f33KXOLtqdmxO6ReTdD+9ZWOUsGZ/6DQhkgM1hxvGaYlrUBlv/0dxTn9kNX9r5SNOrBd2lv6kYqzuiT6iSTLvVKdcBw=
  app: sleepy-forest-52031
