--table definition

CREATE TABLE ADDRESS (
  ADDRESS_ID   NUMBER NOT NULL,
  STREET       VARCHAR2(255),
  POST_CODE    VARCHAR2(10),
  CITY         VARCHAR2(255),
  COUNTRY_CODE VARCHAR2(3),
  CREATE_DATE  DATE DEFAULT sysdate
);

CREATE TABLE COUNTRIES (
  COUNTRY_CODE VARCHAR(3) NOT NULL,
  COUNTRY_NAME VARCHAR2(100),
  POST_CODE_REGEXP VARCHAR2(255)
);

CREATE TABLE CURRENCIES (
  CURRENCY_ID   NUMBER NOT NULL,
  CURRENCY_CODE VARCHAR2(3),
  COUNTRY_CODE  VARCHAR2(3)
);

CREATE TABLE ROLES (
  ROLE_ID   NUMBER NOT NULL,
  ROLE_NAME VARCHAR2(20),
  ROLE_DESC VARCHAR2(100)
);

CREATE TABLE SETTINGS (
  NAME VARCHAR2(255) NOT NULL,
  VAL  VARCHAR2(255)
);

CREATE TABLE USERS (
  USER_ID       NUMBER NOT NULL,
  USER_NAME     VARCHAR2(100),
  PASSWORD      VARCHAR2(100),
  FIRST_NAME    VARCHAR2(100),
  LAST_NAME     VARCHAR2(100),
  EMAIL_ADDRESS VARCHAR2(255),
  BIRTH_DATE    DATE,
  ADDRESS_ID    NUMBER,
  CREATE_DATE   DATE DEFAULT sysdate
);

CREATE TABLE USER_ROLES (
  USER_ID NUMBER,
  ROLE_ID NUMBER
);

--indices
CREATE UNIQUE INDEX ADDRESS_PK_IDX ON ADDRESS (ADDRESS_ID);
CREATE UNIQUE INDEX COUNTRY_PK_IDX ON COUNTRIES (COUNTRY_CODE);
CREATE UNIQUE INDEX CURRENCY_PK_IDX ON CURRENCIES (CURRENCY_ID);
CREATE UNIQUE INDEX CURRENCY_CODE_IDX ON COUNTRIES (COUNTRY_CODE);
CREATE UNIQUE INDEX ROLE_PK_IDX ON ROLES (ROLE_ID);
CREATE UNIQUE INDEX SETTING_PK_IDX ON SETTINGS (NAME);
CREATE UNIQUE INDEX USER_PK_IDX ON USERS (USER_ID);
CREATE UNIQUE INDEX USER_NAME_IDX ON USERS (USER_NAME);

--primary key
ALTER TABLE ADDRESS ADD (
CONSTRAINT ADDRESS_PK
PRIMARY KEY
  (ADDRESS_ID)
  USING INDEX ADDRESS_PK_IDX);

ALTER TABLE COUNTRIES ADD (
CONSTRAINT COUNTRY_PK
PRIMARY KEY
  (COUNTRY_CODE)
  USING INDEX COUNTRY_PK_IDX);

ALTER TABLE CURRENCIES ADD (
CONSTRAINT CURRENCY_PK
PRIMARY KEY
  (CURRENCY_ID)
  USING INDEX CURRENCY_PK_IDX);

ALTER TABLE ROLES ADD (
CONSTRAINT ROLE_PK
PRIMARY KEY
  (ROLE_ID)
  USING INDEX ROLE_PK_IDX);

ALTER TABLE SETTINGS ADD (
CONSTRAINT SETTING_PK
PRIMARY KEY
  (NAME)
  USING INDEX SETTING_PK_IDX);

ALTER TABLE USERS ADD (
CONSTRAINT USER_PK
PRIMARY KEY
  (USER_ID)
  USING INDEX USER_PK_IDX);

--foreign keys
ALTER TABLE USER_ROLES ADD (
CONSTRAINT USER_ROLES_ROLE_FK
FOREIGN KEY (ROLE_ID)
REFERENCES ROLES (ROLE_ID),
CONSTRAINT USER_ROLES_USER_FK
FOREIGN KEY (USER_ID)
REFERENCES USERS (USER_ID));

ALTER TABLE CURRENCIES ADD (
CONSTRAINT CURRENCY_COUNTRY_FK
FOREIGN KEY (COUNTRY_CODE)
REFERENCES COUNTRIES (COUNTRY_CODE));

--sequences

CREATE SEQUENCE ADDRESS_ID_SEQ
START WITH 1
MINVALUE 1
NOCACHE;

CREATE SEQUENCE USER_ID_SEQ
START WITH 1
MINVALUE 1
NOCACHE;

--DML
INSERT INTO COUNTRIES (COUNTRY_CODE, COUNTRY_NAME) VALUES ('AUS', 'Australia');
INSERT INTO COUNTRIES (COUNTRY_CODE, COUNTRY_NAME) VALUES ('DEU', 'Germany');
INSERT INTO COUNTRIES (COUNTRY_CODE, COUNTRY_NAME) VALUES ('HUN', 'Hungary');
INSERT INTO COUNTRIES (COUNTRY_CODE, COUNTRY_NAME) VALUES ('JPN', 'Japan');
INSERT INTO COUNTRIES (COUNTRY_CODE, COUNTRY_NAME) VALUES ('NZL', 'New Zealand');
INSERT INTO COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, POST_CODE_REGEXP) VALUES ('GBR', 'United Kingdom', '(GIR 0AA)|((([A-Z-[QVX]][0-9][0-9]?)|(([A-Z-[QVX]][A-Z-[IJZ]][0-9][0-9]?)|(([A-Z-[QVX]][0-9][A-HJKPSTUW])|([A-Z-[QVX]][A-Z-[IJZ]][0-9][ABEHMNPRVWXY])))) [0-9][A-Z-[CIKMOV]]{2})');
INSERT INTO COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, POST_CODE_REGEXP) VALUES ('USA', 'United States', '^[0-9]{5}(?:-[0-9]{4})?$');

INSERT INTO CURRENCIES (CURRENCY_ID, CURRENCY_CODE, COUNTRY_CODE) VALUES (1, 'EUR', 'DEU');
INSERT INTO CURRENCIES (CURRENCY_ID, CURRENCY_CODE, COUNTRY_CODE) VALUES (2, 'GBP', 'GBR');
INSERT INTO CURRENCIES (CURRENCY_ID, CURRENCY_CODE, COUNTRY_CODE) VALUES (3, 'USD', 'USA');
INSERT INTO CURRENCIES (CURRENCY_ID, CURRENCY_CODE, COUNTRY_CODE) VALUES (4, 'NZD', 'NZL');
INSERT INTO CURRENCIES (CURRENCY_ID, CURRENCY_CODE, COUNTRY_CODE) VALUES (5, 'AUD', 'AUS');
INSERT INTO CURRENCIES (CURRENCY_ID, CURRENCY_CODE, COUNTRY_CODE) VALUES (6, 'JPY', 'JPN');
INSERT INTO CURRENCIES (CURRENCY_ID, CURRENCY_CODE, COUNTRY_CODE) VALUES (7, 'HUF', 'HUN');

INSERT INTO ROLES (ROLE_ID, ROLE_NAME) VALUES (1, 'ROLE_USER');

INSERT INTO SETTINGS (NAME, VAL) VALUES ('CURRENCY_SERVICE_URL', 'http://apilayer.net/api/');
INSERT INTO SETTINGS (NAME, VAL) VALUES ('HISTORY_SHOW_LAST', '10');
INSERT INTO SETTINGS (NAME, VAL) VALUES ('CONNECTION_TIMEOUT', '10');
