--table definition

CREATE TABLE ADDRESS (
    ADDRESS_ID NUMBER,
    STREET VARCHAR2(255),
    POST_CODE VARCHAR2(10),
    CITY VARCHAR2(255),
    COUNTRY_CODE VARCHAR2(3),
    CREATE_DATE DATE default sysdate
);

CREATE TABLE COUNTRIES (
    COUNTRY_CODE VARCHAR(3),
    COUNTRY_NAME VARCHAR2(100);
);

CREATE TABLE CURRENCIES (
    CURRENCY_ID NUMBER,
    CURRENCY_CODE VARCHAR2(3),
    COUNTRY_CODE VARCHAR2(3)
);

CREATE TABLE ROLES (
    ROLE_ID NUMBER,
    ROLE_NAME VARCHAR2(20),
    ROLE_DESC VARCHAR2(100)
)

CREATE TABLE SETTINGS (
    NAME NOT NULL VARCHAR2(255),
    VAL VARCHAR2(255)
);

CREATE TABLE USERS (
    USER_ID NOT NULL NUMBER,
    USER_NAME VARCHAR2(100),
    FIRST_NAME  VARCHAR2(100),
    LAST_NAME VARCHAR2(100),
    EMAIL_ADDRESS VARCHAR2(255),
    BIRTH_DATE DATE,
    USER_ADDRESS_ID NUMBER,
    CREATE_DATE DATE default sysdate,
);

CREATE TABLE USER_ROLES (
    USER_ID NUMBER,
    ROLE_ID NUMBER
);

--indices
CREATE UNIQUE INDEX ADDRESS_PK_IDX ON ADDRESS(ADDRESS_ID);
CREATE UNIQUE INDEX COUNTRY_PK_IDX ON COUNTRIES(COUNTRY_CODE);
CREATE UNIQUE INDEX CURRENCY_PK_IDX ON COUNTRIES(CURRENCY_ID);
CREATE UNIQUE INDEX CURRENCY_CODE_IDX ON COUNTRIES(CURRENCY_CODE);
CREATE UNIQUE INDEX ROLE_PK_IDX ON ROLES (ROLE_ID);
CREATE UNIQUE INDEX SETTING_PK_IDX ON SETTINGS (NAME);
CREATE UNIQUE INDEX USER_PK_IDX ON USERS (USER_ID);
CREATE UNIQUE INDEX USER_NAME_IDX ON USERS (USER_NAME);

--primary key
ALTER TABLE ADDRESS ADD (
    CONSTRAINT ADDRESS_PK
    PRIMARY KEY
    (ADDRESS_ID)
    USING INDEX ADDRESS_PK_IDX);

ALTER TABLE COUNTRY ADD (
  CONSTRAINT COUNTRY_PK
  PRIMARY KEY
  (COUNTRY_CODE)
  USING INDEX COUNTRY_PK_IDX);

ALTER TABLE CURRENCIES ADD (
  CONSTRAINT CURRENCY_PK
  PRIMARY KEY
  (CURRENCY_ID)
  USING INDEX CURRENCY_PK_IDX);

ALTER TABLE ROLES ADD (
  CONSTRAINT ROLE_PK
  PRIMARY KEY
  (ROLE_ID)
  USING INDEX ROLE_PK_IDX);

ALTER TABLE SETTINGS ADD (
    CONSTRAINT SETTING_PK
    PRIMARY KEY
    (NAME)
    USING INDEX SETTING_PK_IDX);

ALTER TABLE USERS ADD (
    CONSTRAINT USER_PK
    PRIMARY KEY
    (USER_ID)
    USING INDEX USER_PK_IDX);

--foreign keys
ALTER TABLE USER_ROLES ADD (
  CONSTRAINT USER_ROLES_ROLE_FK
  FOREIGN KEY (ROLE_ID)
  REFERENCES ROLES (ROLE_ID),
  CONSTRAINT USER_ROLES_USER_FK
  FOREIGN KEY (USER_ID)
  REFERENCES USERS (USER_ID));


--sequences

CREATE SEQUENCE ADDRESS_ID_SEQ
  START WITH 1
  MINVALUE 1
  NOCACHE;

CREATE SEQUENCE USER_ID_SEQ
  START WITH 1
  MINVALUE 1
  NOCACHE;

--DML
insert into COUNTRY (COUNTRY_CODE, COUNTRY_NAME) values ('AUS', 'Australia');
insert into COUNTRY (COUNTRY_CODE, COUNTRY_NAME) values ('DEU', 'Germany');
insert into COUNTRY (COUNTRY_CODE, COUNTRY_NAME) values ('HUN', 'Hungary');
insert into COUNTRY (COUNTRY_CODE, COUNTRY_NAME) values ('JPN', 'Japan');
insert into COUNTRY (COUNTRY_CODE, COUNTRY_NAME) values ('NZL', 'New Zealand');
insert into COUNTRY (COUNTRY_CODE, COUNTRY_NAME) values ('GBR', 'United Kingdom');
insert into COUNTRY (COUNTRY_CODE, COUNTRY_NAME) values ('USA', 'United States');

insert into CURRENCIES (CURRENCY_ID, CURRENCY_CODE, COUNTRY_CODE) values (1, 'EUR', 'DEU');
insert into CURRENCIES (CURRENCY_ID, CURRENCY_CODE, COUNTRY_CODE) values (2, 'GBP', 'GBR');
insert into CURRENCIES (CURRENCY_ID, CURRENCY_CODE, COUNTRY_CODE) values (3, 'USD', 'USA');
insert into CURRENCIES (CURRENCY_ID, CURRENCY_CODE, COUNTRY_CODE) values (4, 'NZD', 'NZL');
insert into CURRENCIES (CURRENCY_ID, CURRENCY_CODE, COUNTRY_CODE) values (5, 'AUD', 'AUS');
insert into CURRENCIES (CURRENCY_ID, CURRENCY_CODE, COUNTRY_CODE) values (6, 'JPY', 'JPN');
insert into CURRENCIES (CURRENCY_ID, CURRENCY_CODE, COUNTRY_CODE) values (7, 'HUF', 'HUN');

insert into ROLES (ROLE_ID, ROLE_NAME) values (1, 'ROLE_USER');

insert into SETTINGS ('CURRENCY_SERVICE_URL','http://apilayer.net/api/');
insert into SETTINGS ('HISTORY_SHOW_LAST', '10');
